### ISSUE TITLE
Add a LICENSE to the project

### ISSUE THREAD

**Issue by gpoppino** [MadCoderZ/NewsBotIRC#10]
Decide which [open source or free software](https://choosealicense.com/) license to use for the project, and add it to a LICENSE file in the root directory.

**Comment by gcanosa** [comment]
I was researching about licenses, and I think MIT would be the most permissive and open among the available licenses.

**Comment by gpoppino** [comment]
@berkelioar MIT license is fine by me.

**Comment by gcanosa** [comment]
MIT added.
