### ISSUE TITLE
Create a LOGO for the project

### ISSUE THREAD

**Issue by gcanosa** [MadCoderZ/NewsBotIRC#11]
If agreed this might be a first logo release.
![logo-newsbot-big](https://cloud.githubusercontent.com/assets/19840006/23765577/686576de-04e0-11e7-8038-8eddfccb2bee.png)

**Comment by gpoppino** [comment]
@berkelioar Looks good!

**Comment by gcanosa** [comment]
Added to the README.md as an outside link.
